### ISSUE TITLE
[BUG]: Version error

### ISSUE THREAD

**Issue by ninjaguardian** [KrLite/Bounced#25]
### Which Mod Loader are You Using?

Quilt

### What Happened?

Bounced Fabric 2.1.3 for 1.19.2 crashes and says that its 1.20 not 1.19.2.

### Steps to Reproduce

Download that file. Boot it up.

### Anything Else?

![Crash photo](https://github.com/KessokuTeaTime/Bounced/assets/110734253/1e32635e-cd84-46f5-ad7a-9a435cea9112)

**Comment by KrLite** [comment]
Thanks for reporting! But I suppose you should try the latest `v2.1.4` first. I hope that runs well as I need to inform you that, **Bounced will not provide any further updates for versions below 1.20 since `v3.0.0`, which means that `v2.1.4` is the last version supporting 1.19.2.** What's more, **Bounced** `v2.1.4` is almost the same with `v2.1.2` or lower, so just use the fittest version.

**Comment by ninjaguardian** [comment]
Ok. But on modrinth says 3.0.0 is a 1.19.2 mod so you may want to change that.
