### ISSUE TITLE
Doesn't work with FancyMenu

### ISSUE THREAD

**Issue by orange809** [KrLite/Bounced#4]
Bounced won't work when FancyMenu customizations menu on.

**Comment by KrLite** [comment]
We both modified the Title Screen by mixins so the code may fight against each other and don't work. I'll check it out when I'm free, but this issue may be at a low priority.

**Comment by thrasos-dev** [comment]
Please consider re-visiting this issue, as this is the reason I am removing the Bounced mod.

**Comment by KrLite** [comment]
Sorry, this issue won't be fixed. Below are the reasons:

- **Fancy Menu** already has customizations and animations on the title(for example, *Cave Animation* in the mod drscription), so it would be a mess if **Bounced** also applies animations on it.
- **Fancy Menu** is using a **very highly customized** system on modifying the title screen, so even **Mod Menu** is on the [incompatibility list.](https://fm.keksuccino.dev/en/incompatibility-list) It would take a lot of effort to check out how it works and to modify the system, with a result of uncertaincy and unstable.
- It would be much easier for players to create another bouncing animation for the title in the **Fancy Menu** editor. Although I know nothing about it, but I believe it is a solution as *Cave Animation* as an example.

All in all, this issue won't be fixed because **Fancy Menu** does too much customizations to the title screen, and it would be easier for players to create a title animation using the editor instead of installing another mod like **Bounced.**

So, if it conflicts, just uninstall this simple mod and fall into the arms of **Fancy Menu.** I hope you have fun playing with all the animations and menus!
